# Generated by Django 4.0.6 on 2024-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_employee_createdby_employee_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
