# Generated by Django 4.0.6 on 2024-06-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSheet',
            new_name='TimeSheetControl',
        ),
    ]
