# Generated by Django 4.0.6 on 2024-08-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], default=1),
        ),
    ]
