# Generated by Django 4.0.6 on 2024-06-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('timesheet', '0002_rename_timesheet_timesheetcontrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSheetControl',
            new_name='Timesheet',
        ),
    ]
