# Generated by Django 4.0.6 on 2024-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_timesheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
