# Generated by Django 4.0.6 on 2024-08-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_employee_is_hr'),
        ('timesheet', '0003_timesheet_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('EmployeeID', 'date')},
        ),
    ]
