# Generated by Django 4.0.6 on 2024-07-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_employee_location'),
        ('timesheet', '0004_alter_timesheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='Location',
            field=models.ForeignKey(db_column='Location', default=100, on_delete=django.db.models.deletion.CASCADE, to='catalog.location'),
            preserve_default=False,
        ),
    ]
